import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import AuthSessionProvider from "./providers/session-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row items-center gap-2">
          <Sidebar />
          <div className="flex flex-col items-center h-[88lvh] w-full mr-6 rounded-2xl border-2 border-gray-400 shadow-xl">
            <AuthSessionProvider>
              {children}
            </AuthSessionProvider>
          </div>
        </div>


      </body>
    </html>
  );
}
